collections:
  pages:
    label: Pages
    folder: src/content/pages
    format: json
    files:
      home:
        label: Home
        file: home.json
        fields:
          - name: title
            label: Title
            type: text
          - name: heroCarousel
            label: Hero Carousel
            type: list
            fields:
              - name: image
                label: Image
                type: image
              - name: title
                label: Slide Title
                type: text
                required: false
              - name: description
                label: Slide Description
                type: textarea
                required: false
              - name: link
                label: Link
                type: text
                required: false
              - name: gradient
                label: Gradient
                type: text
                required: false
          - name: aboutSection
            label: About Section
            type: object
            fields:
              - name: title
                label: Section Title
                type: text
              - name: content
                label: Paragraphs
                type: list
                fields:
                  - name: paragraph
                    label: Paragraph
                    type: textarea
          - name: secondaryCarousel
            label: Secondary Carousel
            type: object
            fields:
              - name: slides
                label: Slides
                type: list
                fields:
                  - name: image
                    label# filepath: /Users/jamesabney-hastings/Documents/Zodono/Clients/Vasari/vasari-astro/.pages.yml
collections:
  pages:
    label: Pages
    folder: src/content/pages
    format: json
    files:
      home:
        label: Home
        file: home.json
        fields:
          - name: title
            label: Title
            type: text
          - name: heroCarousel
            label: Hero Carousel
            type: list
            fields:
              - name: image
                label: Image
                type: image
              - name: title
                label: Slide Title
                type: text
                required: false
              - name: description
                label: Slide Description
                type: textarea
                required: false
              - name: link
                label: Link
                type: text
                required: false
              - name: gradient
                label: Gradient
                type: text
                required: false
          - name: aboutSection
            label: About Section
            type: object
            fields:
              - name: title
                label: Section Title
                type: text
              - name: content
                label: Paragraphs
                type: list
                fields:
                  - name: paragraph
                    label: Paragraph
                    type: textarea
          - name: secondaryCarousel
            label: Secondary Carousel
            type: object
            fields:
              - name: slides
                label: Slides
                type: list
                fields:
                  - name: image
                    label: Image
                    type: image
                  - name: text
                    label: Slide Text
                    type: textarea
                    required: false