media:
  input: public/uploads
  output: /uploads

content:
  - name: "home"
    label: "Home Page"
    type: file
    path: "src/content/home/home.json"
    fields:
      - name: title
        label: Title
        type: string

      - name: heroCarousel
        label: Hero Carousel
        type: object     # Use object for structured fields
        list: true       # This makes the field an array
        fields:          # Inner fields define the structure of each item
          - name: image
            label: Image
            type: image
          - name: alt
            label: Alt Text
            type: string
            required: false

      - name: aboutSection
        label: About Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: content
            label: Content
            type: rich-text
            options:
              media: false
              output: html

      - name: secondaryCarousel
        label: Secondary Carousel
        type: object
        fields:
          - name: slides
            label: Slides
            type: object
            list: true
            fields:
              - name: image
                label: Image
                type: image
              - name: text
                label: Text
                type: rich-text
                options:
                  media: false
                  output: html
                required: false
              - name: alt
                label: Alt Text
                type: string
                required: false

      - name: textBlock
        label: Text Block
        type: object
        fields:
          - name: content
            label: Content
            type: rich-text
            options:
              media: false
              output: html

  - name: "about"
    label: "About Page"
    type: file
    path: "src/content/pages/about.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Content
        type: rich-text
        options:
          media: false

  - name: "services"
    label: "Services Page"
    type: file
    path: "src/content/services/services.json"
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Content
        type: rich-text
        options:
          media: false
      - name: services
        label: Service Blocks
        type: object
        list: true
        fields:
          - name: title
            label: Title
            type: string
          - name: content
            label: Content
            type: text # keep plain text, render with markdown-it in Astro
          - name: image
            label: Image
            type: image
            required: false

  - name: "projects"
    label: "Projects Page"
    type: file
    path: "src/content/projects/projects.json"
    fields:
      - name: title
        label: Page Title
        type: string
      - name: description
        label: Page Description
        type: text
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body Content
        type: markdown
        options:
          media: true
          output: raw
      - name: projects
        label: Individual Projects
        type: object
        list: true
        fields:
          - name: title
            label: Project Title
            type: string
          - name: heroImage
            label: Project Hero Image
            type: image
          - name: content
            label: Project Description
            type: markdown
            options:
              media: true
              output: raw
          - name: images
            label: Gallery Images
            type: object
            list: true
            fields:
              - name: src
                label: Image
                type: image
              - name: alt
                label: Alt Text
                type: string
                required: false


collections:
  - name: "pages"
    label: "Pages"
    files:
      - "home"
      - "about"
      - "services"
      - "projects"
