media:
  input: public/uploads
  output: /uploads

content:
  - name: "home"
    label: "Home Page"
    type: file
    path: "src/content/pages/home.json"
    fields:
      - name: title
        label: Title
        type: string

      - name: heroCarousel
        label: Hero Carousel
        type: list
        fields:
          - name: image
            label: Image
            type: image
          - name: title
            label: Title
            type: string
            required: false
          - name: description
            label: Description
            type: text
            required: false
          - name: link
            label: Link
            type: string
            required: false
          - name: gradient
            label: Gradient
            type: string
            required: false

      - name: aboutSection
        label: About Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: content
            label: Content
            type: list
            field:
              name: paragraph
              label: Paragraph
              type: text

      - name: secondaryCarousel
        label: Secondary Carousel
        type: object
        fields:
          - name: slides
            label: Slides
            type: list
            fields:
              - name: image
                label: Image
                type: image
              - name: text
                label: Text
                type: text
                required: false

      - name: textBlock
        label: Text Block
        type: object
        fields:
          - name: content
            label: Content
            type: text
