files:
  - label: "Home Page"
    name: "home"
    path: "src/content/pages/home.json"
    format: json
    fields:
      - name: title
        label: Title
        type: text

      - name: heroCarousel
        label: Hero Carousel
        type: list
        fields:
          - name: image
            label: Image
            type: file
            allow_multiple: false
          - name: title
            label: Title
            type: text
            required: false
          - name: description
            label: Description
            type: text
            required: false
          - name: link
            label: Link
            type: text
            required: false
          - name: gradient
            label: Gradient
            type: text
            required: false

      - name: aboutSection
        label: About Section
        type: object
        fields:
          - name: title
            label: Title
            type: text
          - name: content
            label: Content
            type: list
            field:
              name: paragraph
              label: Paragraph
              type: text

      - name: secondaryCarousel
        label: Secondary Carousel
        type: object
        fields:
          - name: slides
            label: Slides
            type: list
            fields:
              - name: image
                label: Image
                type: file
                allow_multiple: false
              - name: text
                label: Text
                type: text
                required: false

      - name: textBlock
        label: Text Block
        type: object
        fields:
          - name: content
            label: Content
            type: textarea
