backend:
  name: github
  repo: jabneyhastings/vasari-astro # Replace with your repo
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/pages/home.json"
        fields:
          - { name: "title", label: "Page Title", widget: "string" }
          - name: "carousel"
            label: "Image Carousel"
            widget: "list"
            fields:
              - { name: "image", label: "Image", widget: "image" }
              - { name: "title", label: "Title", widget: "string", required: false }
              - { name: "description", label: "Description", widget: "text", required: false }
              - { name: "link", label: "Link", widget: "string", required: false }