backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/pages/home.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          
          - name: "heroCarousel"
            label: "Hero Carousel"
            widget: "list"
            fields:
              - { name: "image", label: "Image", widget: "image" }
              - { name: "alt", label: "Alt Text", widget: "string", required: false }
          
          - name: "aboutSection"
            label: "About Section"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "content", label: "Content", widget: "markdown" }
          
          - name: "secondaryCarousel"
            label: "Secondary Carousel"
            widget: "object"
            fields:
              - name: "slides"
                label: "Slides"
                widget: "list"
                fields:
                  - { name: "image", label: "Image", widget: "image" }
                  - { name: "text", label: "Text", widget: "markdown", required: false }
                  - { name: "alt", label: "Alt Text", widget: "string", required: false }
          
          - name: "textBlock"
            label: "Text Block"
            widget: "object"
            fields:
              - { name: "content", label: "Content", widget: "markdown" }
      
      - name: "about"
        label: "About Page"
        file: "src/content/pages/about.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - { name: "heroImage", label: "Hero Image", widget: "image" }
          - { name: "content", label: "Content", widget: "markdown" }
      
      - name: "services"
        label: "Services Page"
        file: "src/content/pages/services.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - { name: "heroImage", label: "Hero Image", widget: "image" }
          - { name: "content", label: "Content", widget: "markdown" }